---
# file: roles/node1/tasks/main.yml
- name: add node2 at /etc/hosts
  sudo: yes
  lineinfile: >-
    dest=/etc/hosts
    line='192.168.33.12  node2'
    backup=yes
  tags: node1

- name: unarchive python27.
  sudo: yes
  unarchive: >
        src={{ item.download_dir }}/{{ item.tarball }}
        dest={{ item.download_dir }}/
        creates=no
        copy=no
  with_items: python27
  tags: python27

- name: configure python27
  sudo: yes
  command: >
    ./configure
    --prefix={{ item.install_dir }}
    chdir={{ item.download_dir }}/{{ item.item_dir }}
  with_items:
    python27
  tags: python27

- name: make python27
  sudo: yes
  command: >
    make
    chdir={{ item.download_dir }}/{{ item.item_dir }}
  with_items:
    python27
  tags: python27

- name: make install python27
  sudo: yes
  command: >
    make install
    chdir={{ item.download_dir }}/{{ item.item_dir }}
  with_items:
    python27
  tags: python27

- name: download pip install script
  sudo: yes
  get_url: >
    url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py
    dest={{ item.download_dir }}
  with_items:
    pip
  tags: pip

- name: install pip
  sudo: yes
  command: >
    python {{ item.install_script }}
    chdir={{ item.download_dir }}
  with_items:
    pip
  tags: pip

- name: install ansible
  sudo: yes
  yum: pkg=ansible-{{ item.version }} state=installed
  with_items:
    ansible
  tags: ansible
