---
# roles/python27/tasks/main.yml
- name: be sure zlib-devel, bzip2-devel, openssl-devel, ncurses-devel, sqlite-devel, tk-devel are installed
  sudo: yes
  yum: pkg={{ item }} state=installed
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - expat-devel
    - tcl-devel
    - gdbm-devel
    - libbsd-devel
  tags: python27

- name: download python2.7.8.
  sudo: yes
  get_url: >
      url={{python27_download_base_url}}/{{item.tarball}}
      dest={{python27_download_dir}}/{{item.tarball}}
  with_items: python27
  tags: python27

